apiVersion: v1
kind: PersistentVolume
metadata:
    name: data
    namespace: kube-logging
spec:
    capacity:
        storage: 5Gi
    accessModes: 
      - ReadWriteOnce 
    persistentVolumeReclaimPolicy: Retain 
    storageClassName: data 
    local: 
        path: /mnt/disk/vol1 
    nodeAffinity: 
        required: 
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname 
                    operator: In 
                    values:
                      - kind-control-plane
