apiVersion: v1
kind: Pod
metadata:
    name: nginx-with-tmpfs
spec:
    containers:
    - name: nginx
      image: nginx
      volumeMounts:
      - name: www
        mountPath: /usr/share/nginx/html
    volumes:
    - name: www
      emptyDir:
          medium: Memory
          sizeLimit: "1Gi"


