version: "3"

services:
  rng:
    build: dockercoins/rng
    image: yaowenqiang/rng:${TAG-latest}
    deploy:
      mode: global

  hasher:
    build: dockercoins/hasher
    image: yaowenqiang/hasher:${TAG-latest}

  webui:
    build: dockercoins/webui
    image: yaowenqiang/webui:${TAG-latest}
    ports:
    - "8000:80"

  redis:
    image: redis

  worker:
    build: dockercoins/worker
    image: yaowenqiang/worker:${TAG-latest}
    deploy:
      replicas: 10

